### ISSUE TITLE
Running via IIS

### ISSUE THREAD

**Issue by Gerkiz** [TannerReynolds/ShareS#12]
Hello,

I'm trying to run this through IIS Rewrite module as a subfolder.
`https://xyz.com/upload`

Browsing `https://xyz.com/upload` works fine but the paths however are broken, since they all point to the root domain `https://xyz.com`.

I could just switch the paths in each file (under `src/app/`) but that seems like taking the wrong path.
Any idea on how one would be able to fix this?

If not for IIS then I'd love to know how I could do this on nginx.

Thank you advance!

**Comment by TannerReynolds** [comment]
Sorry, I do not know much about how IIS works, if you could go into further detail explaining how you're running it alongside the node app (and what the behavior should be vs what it's doing), I could help you more. My lack of understanding the issue is why I cannot yet create a dev branch addressing this issue.
I personally run ShareS in an Nginx reverse proxy. Here are some simple instructions on how to get that running for you: https://medium.com/@utkarsh_verma/configure-nginx-as-a-web-server-and-reverse-proxy-for-nodejs-application-on-aws-ubuntu-16-04-server-872922e21d38

The commands and such are in bash, but all you really need to take from that article is this bit of code
```
server {
    listen 80;
    server_name your_domain.com;
    location / {
        proxy_pass http://private_ip_address:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
     }
}
```

Once you have Nginx setup, use that in your config file, replacing the information with what you're using, then reload nginx. This sets up a reverse proxy that will point traffic to your node server, along with whatever else you want to add to your reverse proxy.

**Comment by Gerkiz** [comment]
Thank you! 👍 I solved this by completely removing all the routes to the webpage and just having the APIs so ShareX works.
